// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface LogTraceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.LogTraceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
