// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

/**
 * Protobuf type {@code profilence.zeta.NodeUpdated}
 */
public  final class NodeUpdated extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:profilence.zeta.NodeUpdated)
    NodeUpdatedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeUpdated.newBuilder() to construct.
  private NodeUpdated(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeUpdated() {
    nodeId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NodeUpdated();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NodeUpdated(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeId_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (currentUseCase_ != null) {
              subBuilder = currentUseCase_.toBuilder();
            }
            currentUseCase_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentUseCase_);
              currentUseCase_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (runState_ != null) {
              subBuilder = runState_.toBuilder();
            }
            runState_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(runState_);
              runState_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (currentRunId_ != null) {
              subBuilder = currentRunId_.toBuilder();
            }
            currentRunId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentRunId_);
              currentRunId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (nodeState_ != null) {
              subBuilder = nodeState_.toBuilder();
            }
            nodeState_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nodeState_);
              nodeState_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (pool_ != null) {
              subBuilder = pool_.toBuilder();
            }
            pool_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pool_);
              pool_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (variables_ != null) {
              subBuilder = variables_.toBuilder();
            }
            variables_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(variables_);
              variables_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_NodeUpdated_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_NodeUpdated_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.profilence.zeta.NodeUpdated.class, com.profilence.zeta.NodeUpdated.Builder.class);
  }

  public static final int NODE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object nodeId_;
  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  public java.lang.String getNodeId() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeId_ = s;
      return s;
    }
  }
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_USE_CASE_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue currentUseCase_;
  /**
   * <code>.google.protobuf.StringValue current_use_case = 3;</code>
   * @return Whether the currentUseCase field is set.
   */
  public boolean hasCurrentUseCase() {
    return currentUseCase_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue current_use_case = 3;</code>
   * @return The currentUseCase.
   */
  public com.google.protobuf.StringValue getCurrentUseCase() {
    return currentUseCase_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : currentUseCase_;
  }
  /**
   * <code>.google.protobuf.StringValue current_use_case = 3;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getCurrentUseCaseOrBuilder() {
    return getCurrentUseCase();
  }

  public static final int RUN_STATE_FIELD_NUMBER = 4;
  private com.google.protobuf.Int32Value runState_;
  /**
   * <code>.google.protobuf.Int32Value run_state = 4;</code>
   * @return Whether the runState field is set.
   */
  public boolean hasRunState() {
    return runState_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value run_state = 4;</code>
   * @return The runState.
   */
  public com.google.protobuf.Int32Value getRunState() {
    return runState_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : runState_;
  }
  /**
   * <code>.google.protobuf.Int32Value run_state = 4;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getRunStateOrBuilder() {
    return getRunState();
  }

  public static final int CURRENT_RUN_ID_FIELD_NUMBER = 5;
  private com.google.protobuf.StringValue currentRunId_;
  /**
   * <code>.google.protobuf.StringValue current_run_id = 5;</code>
   * @return Whether the currentRunId field is set.
   */
  public boolean hasCurrentRunId() {
    return currentRunId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue current_run_id = 5;</code>
   * @return The currentRunId.
   */
  public com.google.protobuf.StringValue getCurrentRunId() {
    return currentRunId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : currentRunId_;
  }
  /**
   * <code>.google.protobuf.StringValue current_run_id = 5;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getCurrentRunIdOrBuilder() {
    return getCurrentRunId();
  }

  public static final int NODE_STATE_FIELD_NUMBER = 6;
  private com.google.protobuf.Int32Value nodeState_;
  /**
   * <code>.google.protobuf.Int32Value node_state = 6;</code>
   * @return Whether the nodeState field is set.
   */
  public boolean hasNodeState() {
    return nodeState_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value node_state = 6;</code>
   * @return The nodeState.
   */
  public com.google.protobuf.Int32Value getNodeState() {
    return nodeState_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : nodeState_;
  }
  /**
   * <code>.google.protobuf.Int32Value node_state = 6;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getNodeStateOrBuilder() {
    return getNodeState();
  }

  public static final int POOL_FIELD_NUMBER = 7;
  private com.google.protobuf.StringValue pool_;
  /**
   * <code>.google.protobuf.StringValue pool = 7;</code>
   * @return Whether the pool field is set.
   */
  public boolean hasPool() {
    return pool_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue pool = 7;</code>
   * @return The pool.
   */
  public com.google.protobuf.StringValue getPool() {
    return pool_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : pool_;
  }
  /**
   * <code>.google.protobuf.StringValue pool = 7;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getPoolOrBuilder() {
    return getPool();
  }

  public static final int VARIABLES_FIELD_NUMBER = 8;
  private com.google.protobuf.StringValue variables_;
  /**
   * <code>.google.protobuf.StringValue variables = 8;</code>
   * @return Whether the variables field is set.
   */
  public boolean hasVariables() {
    return variables_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue variables = 8;</code>
   * @return The variables.
   */
  public com.google.protobuf.StringValue getVariables() {
    return variables_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : variables_;
  }
  /**
   * <code>.google.protobuf.StringValue variables = 8;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getVariablesOrBuilder() {
    return getVariables();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNodeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
    }
    if (currentUseCase_ != null) {
      output.writeMessage(3, getCurrentUseCase());
    }
    if (runState_ != null) {
      output.writeMessage(4, getRunState());
    }
    if (currentRunId_ != null) {
      output.writeMessage(5, getCurrentRunId());
    }
    if (nodeState_ != null) {
      output.writeMessage(6, getNodeState());
    }
    if (pool_ != null) {
      output.writeMessage(7, getPool());
    }
    if (variables_ != null) {
      output.writeMessage(8, getVariables());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNodeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
    }
    if (currentUseCase_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCurrentUseCase());
    }
    if (runState_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRunState());
    }
    if (currentRunId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCurrentRunId());
    }
    if (nodeState_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getNodeState());
    }
    if (pool_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getPool());
    }
    if (variables_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getVariables());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.profilence.zeta.NodeUpdated)) {
      return super.equals(obj);
    }
    com.profilence.zeta.NodeUpdated other = (com.profilence.zeta.NodeUpdated) obj;

    if (!getNodeId()
        .equals(other.getNodeId())) return false;
    if (hasCurrentUseCase() != other.hasCurrentUseCase()) return false;
    if (hasCurrentUseCase()) {
      if (!getCurrentUseCase()
          .equals(other.getCurrentUseCase())) return false;
    }
    if (hasRunState() != other.hasRunState()) return false;
    if (hasRunState()) {
      if (!getRunState()
          .equals(other.getRunState())) return false;
    }
    if (hasCurrentRunId() != other.hasCurrentRunId()) return false;
    if (hasCurrentRunId()) {
      if (!getCurrentRunId()
          .equals(other.getCurrentRunId())) return false;
    }
    if (hasNodeState() != other.hasNodeState()) return false;
    if (hasNodeState()) {
      if (!getNodeState()
          .equals(other.getNodeState())) return false;
    }
    if (hasPool() != other.hasPool()) return false;
    if (hasPool()) {
      if (!getPool()
          .equals(other.getPool())) return false;
    }
    if (hasVariables() != other.hasVariables()) return false;
    if (hasVariables()) {
      if (!getVariables()
          .equals(other.getVariables())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId().hashCode();
    if (hasCurrentUseCase()) {
      hash = (37 * hash) + CURRENT_USE_CASE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentUseCase().hashCode();
    }
    if (hasRunState()) {
      hash = (37 * hash) + RUN_STATE_FIELD_NUMBER;
      hash = (53 * hash) + getRunState().hashCode();
    }
    if (hasCurrentRunId()) {
      hash = (37 * hash) + CURRENT_RUN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRunId().hashCode();
    }
    if (hasNodeState()) {
      hash = (37 * hash) + NODE_STATE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeState().hashCode();
    }
    if (hasPool()) {
      hash = (37 * hash) + POOL_FIELD_NUMBER;
      hash = (53 * hash) + getPool().hashCode();
    }
    if (hasVariables()) {
      hash = (37 * hash) + VARIABLES_FIELD_NUMBER;
      hash = (53 * hash) + getVariables().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.profilence.zeta.NodeUpdated parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.profilence.zeta.NodeUpdated parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.profilence.zeta.NodeUpdated parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.profilence.zeta.NodeUpdated parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.profilence.zeta.NodeUpdated prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profilence.zeta.NodeUpdated}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profilence.zeta.NodeUpdated)
      com.profilence.zeta.NodeUpdatedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_NodeUpdated_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_NodeUpdated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.profilence.zeta.NodeUpdated.class, com.profilence.zeta.NodeUpdated.Builder.class);
    }

    // Construct using com.profilence.zeta.NodeUpdated.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeId_ = "";

      if (currentUseCaseBuilder_ == null) {
        currentUseCase_ = null;
      } else {
        currentUseCase_ = null;
        currentUseCaseBuilder_ = null;
      }
      if (runStateBuilder_ == null) {
        runState_ = null;
      } else {
        runState_ = null;
        runStateBuilder_ = null;
      }
      if (currentRunIdBuilder_ == null) {
        currentRunId_ = null;
      } else {
        currentRunId_ = null;
        currentRunIdBuilder_ = null;
      }
      if (nodeStateBuilder_ == null) {
        nodeState_ = null;
      } else {
        nodeState_ = null;
        nodeStateBuilder_ = null;
      }
      if (poolBuilder_ == null) {
        pool_ = null;
      } else {
        pool_ = null;
        poolBuilder_ = null;
      }
      if (variablesBuilder_ == null) {
        variables_ = null;
      } else {
        variables_ = null;
        variablesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_NodeUpdated_descriptor;
    }

    @java.lang.Override
    public com.profilence.zeta.NodeUpdated getDefaultInstanceForType() {
      return com.profilence.zeta.NodeUpdated.getDefaultInstance();
    }

    @java.lang.Override
    public com.profilence.zeta.NodeUpdated build() {
      com.profilence.zeta.NodeUpdated result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.profilence.zeta.NodeUpdated buildPartial() {
      com.profilence.zeta.NodeUpdated result = new com.profilence.zeta.NodeUpdated(this);
      result.nodeId_ = nodeId_;
      if (currentUseCaseBuilder_ == null) {
        result.currentUseCase_ = currentUseCase_;
      } else {
        result.currentUseCase_ = currentUseCaseBuilder_.build();
      }
      if (runStateBuilder_ == null) {
        result.runState_ = runState_;
      } else {
        result.runState_ = runStateBuilder_.build();
      }
      if (currentRunIdBuilder_ == null) {
        result.currentRunId_ = currentRunId_;
      } else {
        result.currentRunId_ = currentRunIdBuilder_.build();
      }
      if (nodeStateBuilder_ == null) {
        result.nodeState_ = nodeState_;
      } else {
        result.nodeState_ = nodeStateBuilder_.build();
      }
      if (poolBuilder_ == null) {
        result.pool_ = pool_;
      } else {
        result.pool_ = poolBuilder_.build();
      }
      if (variablesBuilder_ == null) {
        result.variables_ = variables_;
      } else {
        result.variables_ = variablesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.profilence.zeta.NodeUpdated) {
        return mergeFrom((com.profilence.zeta.NodeUpdated)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.profilence.zeta.NodeUpdated other) {
      if (other == com.profilence.zeta.NodeUpdated.getDefaultInstance()) return this;
      if (!other.getNodeId().isEmpty()) {
        nodeId_ = other.nodeId_;
        onChanged();
      }
      if (other.hasCurrentUseCase()) {
        mergeCurrentUseCase(other.getCurrentUseCase());
      }
      if (other.hasRunState()) {
        mergeRunState(other.getRunState());
      }
      if (other.hasCurrentRunId()) {
        mergeCurrentRunId(other.getCurrentRunId());
      }
      if (other.hasNodeState()) {
        mergeNodeState(other.getNodeState());
      }
      if (other.hasPool()) {
        mergePool(other.getPool());
      }
      if (other.hasVariables()) {
        mergeVariables(other.getVariables());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.profilence.zeta.NodeUpdated parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.profilence.zeta.NodeUpdated) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object nodeId_ = "";
    /**
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      
      nodeId_ = getDefaultInstance().getNodeId();
      onChanged();
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue currentUseCase_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> currentUseCaseBuilder_;
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     * @return Whether the currentUseCase field is set.
     */
    public boolean hasCurrentUseCase() {
      return currentUseCaseBuilder_ != null || currentUseCase_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     * @return The currentUseCase.
     */
    public com.google.protobuf.StringValue getCurrentUseCase() {
      if (currentUseCaseBuilder_ == null) {
        return currentUseCase_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : currentUseCase_;
      } else {
        return currentUseCaseBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     */
    public Builder setCurrentUseCase(com.google.protobuf.StringValue value) {
      if (currentUseCaseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentUseCase_ = value;
        onChanged();
      } else {
        currentUseCaseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     */
    public Builder setCurrentUseCase(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (currentUseCaseBuilder_ == null) {
        currentUseCase_ = builderForValue.build();
        onChanged();
      } else {
        currentUseCaseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     */
    public Builder mergeCurrentUseCase(com.google.protobuf.StringValue value) {
      if (currentUseCaseBuilder_ == null) {
        if (currentUseCase_ != null) {
          currentUseCase_ =
            com.google.protobuf.StringValue.newBuilder(currentUseCase_).mergeFrom(value).buildPartial();
        } else {
          currentUseCase_ = value;
        }
        onChanged();
      } else {
        currentUseCaseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     */
    public Builder clearCurrentUseCase() {
      if (currentUseCaseBuilder_ == null) {
        currentUseCase_ = null;
        onChanged();
      } else {
        currentUseCase_ = null;
        currentUseCaseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getCurrentUseCaseBuilder() {
      
      onChanged();
      return getCurrentUseCaseFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getCurrentUseCaseOrBuilder() {
      if (currentUseCaseBuilder_ != null) {
        return currentUseCaseBuilder_.getMessageOrBuilder();
      } else {
        return currentUseCase_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : currentUseCase_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue current_use_case = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getCurrentUseCaseFieldBuilder() {
      if (currentUseCaseBuilder_ == null) {
        currentUseCaseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getCurrentUseCase(),
                getParentForChildren(),
                isClean());
        currentUseCase_ = null;
      }
      return currentUseCaseBuilder_;
    }

    private com.google.protobuf.Int32Value runState_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> runStateBuilder_;
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     * @return Whether the runState field is set.
     */
    public boolean hasRunState() {
      return runStateBuilder_ != null || runState_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     * @return The runState.
     */
    public com.google.protobuf.Int32Value getRunState() {
      if (runStateBuilder_ == null) {
        return runState_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : runState_;
      } else {
        return runStateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     */
    public Builder setRunState(com.google.protobuf.Int32Value value) {
      if (runStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        runState_ = value;
        onChanged();
      } else {
        runStateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     */
    public Builder setRunState(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (runStateBuilder_ == null) {
        runState_ = builderForValue.build();
        onChanged();
      } else {
        runStateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     */
    public Builder mergeRunState(com.google.protobuf.Int32Value value) {
      if (runStateBuilder_ == null) {
        if (runState_ != null) {
          runState_ =
            com.google.protobuf.Int32Value.newBuilder(runState_).mergeFrom(value).buildPartial();
        } else {
          runState_ = value;
        }
        onChanged();
      } else {
        runStateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     */
    public Builder clearRunState() {
      if (runStateBuilder_ == null) {
        runState_ = null;
        onChanged();
      } else {
        runState_ = null;
        runStateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     */
    public com.google.protobuf.Int32Value.Builder getRunStateBuilder() {
      
      onChanged();
      return getRunStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getRunStateOrBuilder() {
      if (runStateBuilder_ != null) {
        return runStateBuilder_.getMessageOrBuilder();
      } else {
        return runState_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : runState_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value run_state = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getRunStateFieldBuilder() {
      if (runStateBuilder_ == null) {
        runStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getRunState(),
                getParentForChildren(),
                isClean());
        runState_ = null;
      }
      return runStateBuilder_;
    }

    private com.google.protobuf.StringValue currentRunId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> currentRunIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     * @return Whether the currentRunId field is set.
     */
    public boolean hasCurrentRunId() {
      return currentRunIdBuilder_ != null || currentRunId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     * @return The currentRunId.
     */
    public com.google.protobuf.StringValue getCurrentRunId() {
      if (currentRunIdBuilder_ == null) {
        return currentRunId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : currentRunId_;
      } else {
        return currentRunIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     */
    public Builder setCurrentRunId(com.google.protobuf.StringValue value) {
      if (currentRunIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentRunId_ = value;
        onChanged();
      } else {
        currentRunIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     */
    public Builder setCurrentRunId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (currentRunIdBuilder_ == null) {
        currentRunId_ = builderForValue.build();
        onChanged();
      } else {
        currentRunIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     */
    public Builder mergeCurrentRunId(com.google.protobuf.StringValue value) {
      if (currentRunIdBuilder_ == null) {
        if (currentRunId_ != null) {
          currentRunId_ =
            com.google.protobuf.StringValue.newBuilder(currentRunId_).mergeFrom(value).buildPartial();
        } else {
          currentRunId_ = value;
        }
        onChanged();
      } else {
        currentRunIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     */
    public Builder clearCurrentRunId() {
      if (currentRunIdBuilder_ == null) {
        currentRunId_ = null;
        onChanged();
      } else {
        currentRunId_ = null;
        currentRunIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     */
    public com.google.protobuf.StringValue.Builder getCurrentRunIdBuilder() {
      
      onChanged();
      return getCurrentRunIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getCurrentRunIdOrBuilder() {
      if (currentRunIdBuilder_ != null) {
        return currentRunIdBuilder_.getMessageOrBuilder();
      } else {
        return currentRunId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : currentRunId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue current_run_id = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getCurrentRunIdFieldBuilder() {
      if (currentRunIdBuilder_ == null) {
        currentRunIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getCurrentRunId(),
                getParentForChildren(),
                isClean());
        currentRunId_ = null;
      }
      return currentRunIdBuilder_;
    }

    private com.google.protobuf.Int32Value nodeState_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> nodeStateBuilder_;
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     * @return Whether the nodeState field is set.
     */
    public boolean hasNodeState() {
      return nodeStateBuilder_ != null || nodeState_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     * @return The nodeState.
     */
    public com.google.protobuf.Int32Value getNodeState() {
      if (nodeStateBuilder_ == null) {
        return nodeState_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : nodeState_;
      } else {
        return nodeStateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     */
    public Builder setNodeState(com.google.protobuf.Int32Value value) {
      if (nodeStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nodeState_ = value;
        onChanged();
      } else {
        nodeStateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     */
    public Builder setNodeState(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (nodeStateBuilder_ == null) {
        nodeState_ = builderForValue.build();
        onChanged();
      } else {
        nodeStateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     */
    public Builder mergeNodeState(com.google.protobuf.Int32Value value) {
      if (nodeStateBuilder_ == null) {
        if (nodeState_ != null) {
          nodeState_ =
            com.google.protobuf.Int32Value.newBuilder(nodeState_).mergeFrom(value).buildPartial();
        } else {
          nodeState_ = value;
        }
        onChanged();
      } else {
        nodeStateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     */
    public Builder clearNodeState() {
      if (nodeStateBuilder_ == null) {
        nodeState_ = null;
        onChanged();
      } else {
        nodeState_ = null;
        nodeStateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     */
    public com.google.protobuf.Int32Value.Builder getNodeStateBuilder() {
      
      onChanged();
      return getNodeStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getNodeStateOrBuilder() {
      if (nodeStateBuilder_ != null) {
        return nodeStateBuilder_.getMessageOrBuilder();
      } else {
        return nodeState_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : nodeState_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value node_state = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getNodeStateFieldBuilder() {
      if (nodeStateBuilder_ == null) {
        nodeStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getNodeState(),
                getParentForChildren(),
                isClean());
        nodeState_ = null;
      }
      return nodeStateBuilder_;
    }

    private com.google.protobuf.StringValue pool_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> poolBuilder_;
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     * @return Whether the pool field is set.
     */
    public boolean hasPool() {
      return poolBuilder_ != null || pool_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     * @return The pool.
     */
    public com.google.protobuf.StringValue getPool() {
      if (poolBuilder_ == null) {
        return pool_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : pool_;
      } else {
        return poolBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     */
    public Builder setPool(com.google.protobuf.StringValue value) {
      if (poolBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pool_ = value;
        onChanged();
      } else {
        poolBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     */
    public Builder setPool(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (poolBuilder_ == null) {
        pool_ = builderForValue.build();
        onChanged();
      } else {
        poolBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     */
    public Builder mergePool(com.google.protobuf.StringValue value) {
      if (poolBuilder_ == null) {
        if (pool_ != null) {
          pool_ =
            com.google.protobuf.StringValue.newBuilder(pool_).mergeFrom(value).buildPartial();
        } else {
          pool_ = value;
        }
        onChanged();
      } else {
        poolBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     */
    public Builder clearPool() {
      if (poolBuilder_ == null) {
        pool_ = null;
        onChanged();
      } else {
        pool_ = null;
        poolBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     */
    public com.google.protobuf.StringValue.Builder getPoolBuilder() {
      
      onChanged();
      return getPoolFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getPoolOrBuilder() {
      if (poolBuilder_ != null) {
        return poolBuilder_.getMessageOrBuilder();
      } else {
        return pool_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : pool_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue pool = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getPoolFieldBuilder() {
      if (poolBuilder_ == null) {
        poolBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getPool(),
                getParentForChildren(),
                isClean());
        pool_ = null;
      }
      return poolBuilder_;
    }

    private com.google.protobuf.StringValue variables_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> variablesBuilder_;
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     * @return Whether the variables field is set.
     */
    public boolean hasVariables() {
      return variablesBuilder_ != null || variables_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     * @return The variables.
     */
    public com.google.protobuf.StringValue getVariables() {
      if (variablesBuilder_ == null) {
        return variables_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : variables_;
      } else {
        return variablesBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     */
    public Builder setVariables(com.google.protobuf.StringValue value) {
      if (variablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        variables_ = value;
        onChanged();
      } else {
        variablesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     */
    public Builder setVariables(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (variablesBuilder_ == null) {
        variables_ = builderForValue.build();
        onChanged();
      } else {
        variablesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     */
    public Builder mergeVariables(com.google.protobuf.StringValue value) {
      if (variablesBuilder_ == null) {
        if (variables_ != null) {
          variables_ =
            com.google.protobuf.StringValue.newBuilder(variables_).mergeFrom(value).buildPartial();
        } else {
          variables_ = value;
        }
        onChanged();
      } else {
        variablesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     */
    public Builder clearVariables() {
      if (variablesBuilder_ == null) {
        variables_ = null;
        onChanged();
      } else {
        variables_ = null;
        variablesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     */
    public com.google.protobuf.StringValue.Builder getVariablesBuilder() {
      
      onChanged();
      return getVariablesFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getVariablesOrBuilder() {
      if (variablesBuilder_ != null) {
        return variablesBuilder_.getMessageOrBuilder();
      } else {
        return variables_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : variables_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue variables = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getVariablesFieldBuilder() {
      if (variablesBuilder_ == null) {
        variablesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getVariables(),
                getParentForChildren(),
                isClean());
        variables_ = null;
      }
      return variablesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:profilence.zeta.NodeUpdated)
  }

  // @@protoc_insertion_point(class_scope:profilence.zeta.NodeUpdated)
  private static final com.profilence.zeta.NodeUpdated DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.profilence.zeta.NodeUpdated();
  }

  public static com.profilence.zeta.NodeUpdated getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeUpdated>
      PARSER = new com.google.protobuf.AbstractParser<NodeUpdated>() {
    @java.lang.Override
    public NodeUpdated parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NodeUpdated(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NodeUpdated> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeUpdated> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.profilence.zeta.NodeUpdated getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

