// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface PingMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.PingMessage)
    com.google.protobuf.MessageOrBuilder {
}
