// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public final class DriverProto {
  private DriverProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_StartRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_StartRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_StartRunRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_StartRunRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_PingMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_PingMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_PongMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_PongMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_StartRunResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_StartRunResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_UseCaseStartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_UseCaseStartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_LogStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_LogStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_LogTraceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_LogTraceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_UseCaseEndRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_UseCaseEndRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_StopRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_StopRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_TestRequestMessageWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_TestRequestMessageWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_TestStopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_TestStopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_TestStartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_TestStartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_TestStartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_TestStartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_TestStartRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_TestStartRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_NodeAdded_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_NodeAdded_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_NodeRemoved_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_NodeRemoved_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_NodeUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_NodeUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DynamicSeriesInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DynamicSeriesInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DynamicSingleSeriesUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DynamicSingleSeriesUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DynamicProcessSingleSeriesUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DynamicProcessSingleSeriesUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_DeviceLogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_DeviceLogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_ResetEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_ResetEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_ResetEntry_ReasonsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_ResetEntry_ReasonsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_ResetEntry_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_ResetEntry_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_EventEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_EventEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profilence_zeta_PingRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profilence_zeta_PingRunRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027connector_service.proto\022\017profilence.ze" +
      "ta\032\016wrappers.proto\032\013empty.proto\"\346\002\n\017Star" +
      "tRunRequest\022\020\n\010run_name\030\001 \001(\t\022\020\n\010set_nam" +
      "e\030\002 \001(\t\022\017\n\007project\030\003 \001(\t\022\017\n\007version\030\004 \001(" +
      "\t\022\035\n\025primary_device_serial\030\005 \001(\t\022\037\n\027seco" +
      "ndary_device_serial\030\006 \001(\t\022\032\n\022profiling_s" +
      "ettings\030\007 \001(\t\0228\n\004tags\030\010 \003(\0132*.profilence" +
      ".zeta.StartRunRequest.TagsEntry\022\033\n\023prima" +
      "ry_device_type\030\t \001(\t\022\035\n\025secondary_device" +
      "_type\030\n \001(\t\022\016\n\006run_id\030\013 \001(\t\032+\n\tTagsEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\r\n\013Ping" +
      "Message\"\035\n\013PongMessage\022\016\n\006result\030\001 \001(\005\"\"" +
      "\n\020StartRunResponse\022\016\n\006run_id\030\001 \001(\t\"\311\001\n\023U" +
      "seCaseStartRequest\022\016\n\006run_id\030\001 \001(\t\022\025\n\rus" +
      "e_case_name\030\002 \001(\t\022\023\n\013use_case_id\030\003 \001(\t\022\026" +
      "\n\016target_process\030\004 \001(\t\022\026\n\016requirement_id" +
      "\030\005 \001(\t\022\021\n\ttest_type\030\006 \001(\005\022\034\n\024test_case_g" +
      "roup_name\030\007 \001(\t\022\025\n\rtest_set_name\030\010 \001(\t\"\262" +
      "\002\n\016LogStepRequest\022\016\n\006run_id\030\001 \001(\t\022\021\n\tste" +
      "p_name\030\002 \001(\t\022\016\n\006result\030\003 \001(\010\022\027\n\017take_scr" +
      "eenshot\030\004 \001(\010\022\030\n\020screenshot_bytes\030\005 \001(\014\022" +
      ":\n\010stepType\030\006 \001(\0162(.profilence.zeta.LogS" +
      "tepRequest.StepType\"~\n\010StepType\022\010\n\004Idle\020" +
      "\000\022\013\n\007Running\020\001\022\n\n\006Paused\020\002\022\016\n\nNotStarted" +
      "\020\003\022\t\n\005Setup\020\004\022\014\n\010TearDown\020\005\022\014\n\010Finished\020" +
      "\006\022\013\n\007Aborted\020\007\022\013\n\007Faulted\020\010\"/\n\017LogTraceR" +
      "equest\022\016\n\006run_id\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\"v\n\021" +
      "UseCaseEndRequest\022\016\n\006run_id\030\001 \001(\t\022\016\n\006res" +
      "ult\030\002 \001(\010\022\025\n\ractiveRunTime\030\003 \001(\003\022\022\n\nfail" +
      "_cause\030\004 \001(\t\022\026\n\016reset_intended\030\005 \001(\010\"9\n\016" +
      "StopRunRequest\022\016\n\006run_id\030\001 \001(\t\022\027\n\017discar" +
      "d_results\030\002 \001(\010\"B\n\031TestRequestMessageWra" +
      "pper\022\024\n\014request_type\030\001 \001(\005\022\017\n\007payload\030\002 " +
      "\001(\014\"0\n\017TestStopRequest\022\035\n\025primary_device" +
      "_serial\030\001 \001(\t\"d\n\021TestStartResponse\022\016\n\006ru" +
      "n_id\030\001 \001(\t\022\022\n\nfail_cause\030\002 \001(\t\022\013\n\003log\030\003 " +
      "\003(\t\022\016\n\006result\030\004 \001(\010\022\016\n\006status\030\005 \001(\t\"\211\002\n\020" +
      "TestStartRequest\022\016\n\006run_id\030\026 \001(\t\022\020\n\010run_" +
      "name\030\002 \001(\t\022\017\n\007node_id\030\005 \001(\t\022\017\n\007project\030\n" +
      " \001(\t\022\017\n\007version\030\020 \001(\t\022\032\n\022test_set_file_p" +
      "ath\030\014 \001(\t\022\017\n\007payload\030\016 \001(\014\0229\n\004tags\030\024 \003(\013" +
      "2+.profilence.zeta.TestStartRequest.Tags" +
      "Entry\022\013\n\003log\030\030 \003(\t\032+\n\tTagsEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"K\n\tNodeAdded\022\017\n\007" +
      "node_id\030\001 \001(\t\022\014\n\004pool\030\004 \001(\t\022\014\n\004type\030\005 \001(" +
      "\t\022\021\n\tvariables\030\014 \001(\t\"\036\n\013NodeRemoved\022\017\n\007n" +
      "ode_id\030\001 \001(\t\"\312\002\n\013NodeUpdated\022\017\n\007node_id\030" +
      "\001 \001(\t\0226\n\020current_use_case\030\003 \001(\0132\034.google" +
      ".protobuf.StringValue\022.\n\trun_state\030\004 \001(\013" +
      "2\033.google.protobuf.Int32Value\0224\n\016current" +
      "_run_id\030\005 \001(\0132\034.google.protobuf.StringVa" +
      "lue\022/\n\nnode_state\030\006 \001(\0132\033.google.protobu" +
      "f.Int32Value\022*\n\004pool\030\007 \001(\0132\034.google.prot" +
      "obuf.StringValue\022/\n\tvariables\030\010 \001(\0132\034.go" +
      "ogle.protobuf.StringValue\"\313\001\n\030DynamicSer" +
      "iesInformation\022\016\n\006run_id\030\001 \001(\t\022\021\n\tseries" +
      "_id\030\002 \001(\t\022\023\n\013series_name\030\003 \001(\t\022\r\n\005group\030" +
      "\004 \001(\t\022\023\n\013y_axis_name\030\005 \001(\t\022\014\n\004unit\030\006 \001(\t" +
      "\022\014\n\004type\030\007 \001(\005\022\021\n\tnamespace\030\010 \001(\t\022\017\n\007pro" +
      "cess\030\t \001(\t\022\023\n\013description\030\n \001(\t\"`\n\031Dynam" +
      "icSingleSeriesUpdate\022\016\n\006run_id\030\001 \001(\t\022\021\n\t" +
      "series_id\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\001\022\r\n\005va" +
      "lue\030\004 \001(\002\"\263\001\n DynamicProcessSingleSeries" +
      "Update\022\016\n\006run_id\030\001 \001(\t\022\021\n\tseries_id\030\002 \001(" +
      "\t\022\017\n\007package\030\003 \001(\t\022\017\n\007process\030\004 \001(\t\022\021\n\tt" +
      "imestamp\030\005 \001(\001\022\r\n\005value\030\006 \001(\002\022(\n\003pid\030\007 \001" +
      "(\0132\033.google.protobuf.Int32Value\"\316\001\n\034Dyna" +
      "micCompositeSeriesUpdate\022\016\n\006run_id\030\001 \001(\t" +
      "\022\021\n\tseries_id\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\001\022I" +
      "\n\006values\030\004 \003(\01329.profilence.zeta.Dynamic" +
      "CompositeSeriesUpdate.ValuesEntry\032-\n\013Val" +
      "uesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\002:\0028\001" +
      "\"\250\002\n#DynamicProcessCompositeSeriesUpdate" +
      "\022\016\n\006run_id\030\001 \001(\t\022\021\n\tseries_id\030\002 \001(\t\022\017\n\007p" +
      "ackage\030\003 \001(\t\022\017\n\007process\030\004 \001(\t\022\021\n\ttimesta" +
      "mp\030\005 \001(\001\022P\n\006values\030\006 \003(\0132@.profilence.ze" +
      "ta.DynamicProcessCompositeSeriesUpdate.V" +
      "aluesEntry\022(\n\003pid\030\007 \001(\0132\033.google.protobu" +
      "f.Int32Value\032-\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\002:\0028\001\"\215\001\n\016DeviceLogEntry\022\016" +
      "\n\006run_id\030\001 \001(\t\022\024\n\014device_index\030\002 \001(\005\022\021\n\t" +
      "timestamp\030\003 \001(\001\022\013\n\003tag\030\004 \001(\t\022\014\n\004data\030\005 \001" +
      "(\t\022\020\n\010priority\030\006 \001(\005\022\025\n\rsource_buffer\030\007 " +
      "\001(\005\"\234\002\n\nResetEntry\022\016\n\006run_id\030\001 \001(\t\022\021\n\tti" +
      "mestamp\030\002 \001(\001\022\014\n\004type\030\003 \001(\005\0229\n\007reasons\030\004" +
      " \003(\0132(.profilence.zeta.ResetEntry.Reason" +
      "sEntry\022?\n\nproperties\030\005 \003(\0132+.profilence." +
      "zeta.ResetEntry.PropertiesEntry\032.\n\014Reaso" +
      "nsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032" +
      "1\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"\235\001\n\nEventEntry\022\016\n\006run_id\030\001 \001(" +
      "\t\022\021\n\ttimestamp\030\002 \001(\001\022\014\n\004type\030\003 \001(\005\022\031\n\021is" +
      "_system_process\030\004 \001(\010\022\014\n\004name\030\005 \001(\t\022\017\n\007p" +
      "rocess\030\006 \001(\t\022\026\n\016exception_type\030\007 \001(\t\022\014\n\004" +
      "data\030\010 \003(\t\" \n\016PingRunRequest\022\016\n\006run_id\030\001" +
      " \001(\t2\300\r\n\020ConnectorService\022D\n\004Ping\022\034.prof" +
      "ilence.zeta.PingMessage\032\034.profilence.zet" +
      "a.PongMessage\"\000\022Q\n\010StartRun\022 .profilence" +
      ".zeta.StartRunRequest\032!.profilence.zeta." +
      "StartRunResponse\"\000\022P\n\016OnUseCaseStart\022$.p" +
      "rofilence.zeta.UseCaseStartRequest\032\026.goo" +
      "gle.protobuf.Empty\"\000\022F\n\tOnLogStep\022\037.prof" +
      "ilence.zeta.LogStepRequest\032\026.google.prot" +
      "obuf.Empty\"\000\022F\n\010LogTrace\022 .profilence.ze" +
      "ta.LogTraceRequest\032\026.google.protobuf.Emp" +
      "ty\"\000\022H\n\tLogDevice\022\037.profilence.zeta.Devi" +
      "ceLogEntry\032\026.google.protobuf.Empty\"\000(\001\022D" +
      "\n\013NotifyReset\022\033.profilence.zeta.ResetEnt" +
      "ry\032\026.google.protobuf.Empty\"\000\022D\n\013NotifyEv" +
      "ent\022\033.profilence.zeta.EventEntry\032\026.googl" +
      "e.protobuf.Empty\"\000\022L\n\014OnUseCaseEnd\022\".pro" +
      "filence.zeta.UseCaseEndRequest\032\026.google." +
      "protobuf.Empty\"\000\022D\n\007StopRun\022\037.profilence" +
      ".zeta.StopRunRequest\032\026.google.protobuf.E" +
      "mpty\"\000\022W\n\020CreateTimeSeries\022).profilence." +
      "zeta.DynamicSeriesInformation\032\026.google.p" +
      "rotobuf.Empty\"\000\022`\n\030UpdateSingleSystemSer" +
      "ies\022*.profilence.zeta.DynamicSingleSerie" +
      "sUpdate\032\026.google.protobuf.Empty\"\000\022h\n\031Upd" +
      "ateSingleProcessSeries\0221.profilence.zeta" +
      ".DynamicProcessSingleSeriesUpdate\032\026.goog" +
      "le.protobuf.Empty\"\000\022f\n\033UpdateCompositeSy" +
      "stemSeries\022-.profilence.zeta.DynamicComp" +
      "ositeSeriesUpdate\032\026.google.protobuf.Empt" +
      "y\"\000\022n\n\034UpdateCompositeProcessSeries\0224.pr" +
      "ofilence.zeta.DynamicProcessCompositeSer" +
      "iesUpdate\032\026.google.protobuf.Empty\"\000\022a\n\027S" +
      "ubscribeToTestRequests\022\026.google.protobuf" +
      ".Empty\032*.profilence.zeta.TestRequestMess" +
      "ageWrapper\"\0000\001\022T\n\024RespondToTestRequest\022\"" +
      ".profilence.zeta.TestStartResponse\032\026.goo" +
      "gle.protobuf.Empty\"\000\022?\n\007AddNode\022\032.profil" +
      "ence.zeta.NodeAdded\032\026.google.protobuf.Em" +
      "pty\"\000\022D\n\nRemoveNode\022\034.profilence.zeta.No" +
      "deRemoved\032\026.google.protobuf.Empty\"\000\022D\n\nU" +
      "pdateNode\022\034.profilence.zeta.NodeUpdated\032" +
      "\026.google.protobuf.Empty\"\000\022D\n\007PingRun\022\037.p" +
      "rofilence.zeta.PingRunRequest\032\026.google.p" +
      "rotobuf.Empty\"\000B$\n\023com.profilence.zetaB\013" +
      "DriverProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_profilence_zeta_StartRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_profilence_zeta_StartRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_StartRunRequest_descriptor,
        new java.lang.String[] { "RunName", "SetName", "Project", "Version", "PrimaryDeviceSerial", "SecondaryDeviceSerial", "ProfilingSettings", "Tags", "PrimaryDeviceType", "SecondaryDeviceType", "RunId", });
    internal_static_profilence_zeta_StartRunRequest_TagsEntry_descriptor =
      internal_static_profilence_zeta_StartRunRequest_descriptor.getNestedTypes().get(0);
    internal_static_profilence_zeta_StartRunRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_StartRunRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_profilence_zeta_PingMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_profilence_zeta_PingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_PingMessage_descriptor,
        new java.lang.String[] { });
    internal_static_profilence_zeta_PongMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_profilence_zeta_PongMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_PongMessage_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_profilence_zeta_StartRunResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_profilence_zeta_StartRunResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_StartRunResponse_descriptor,
        new java.lang.String[] { "RunId", });
    internal_static_profilence_zeta_UseCaseStartRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_profilence_zeta_UseCaseStartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_UseCaseStartRequest_descriptor,
        new java.lang.String[] { "RunId", "UseCaseName", "UseCaseId", "TargetProcess", "RequirementId", "TestType", "TestCaseGroupName", "TestSetName", });
    internal_static_profilence_zeta_LogStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_profilence_zeta_LogStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_LogStepRequest_descriptor,
        new java.lang.String[] { "RunId", "StepName", "Result", "TakeScreenshot", "ScreenshotBytes", "StepType", });
    internal_static_profilence_zeta_LogTraceRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_profilence_zeta_LogTraceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_LogTraceRequest_descriptor,
        new java.lang.String[] { "RunId", "Data", });
    internal_static_profilence_zeta_UseCaseEndRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_profilence_zeta_UseCaseEndRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_UseCaseEndRequest_descriptor,
        new java.lang.String[] { "RunId", "Result", "ActiveRunTime", "FailCause", "ResetIntended", });
    internal_static_profilence_zeta_StopRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_profilence_zeta_StopRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_StopRunRequest_descriptor,
        new java.lang.String[] { "RunId", "DiscardResults", });
    internal_static_profilence_zeta_TestRequestMessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_profilence_zeta_TestRequestMessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_TestRequestMessageWrapper_descriptor,
        new java.lang.String[] { "RequestType", "Payload", });
    internal_static_profilence_zeta_TestStopRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_profilence_zeta_TestStopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_TestStopRequest_descriptor,
        new java.lang.String[] { "PrimaryDeviceSerial", });
    internal_static_profilence_zeta_TestStartResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_profilence_zeta_TestStartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_TestStartResponse_descriptor,
        new java.lang.String[] { "RunId", "FailCause", "Log", "Result", "Status", });
    internal_static_profilence_zeta_TestStartRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_profilence_zeta_TestStartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_TestStartRequest_descriptor,
        new java.lang.String[] { "RunId", "RunName", "NodeId", "Project", "Version", "TestSetFilePath", "Payload", "Tags", "Log", });
    internal_static_profilence_zeta_TestStartRequest_TagsEntry_descriptor =
      internal_static_profilence_zeta_TestStartRequest_descriptor.getNestedTypes().get(0);
    internal_static_profilence_zeta_TestStartRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_TestStartRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_profilence_zeta_NodeAdded_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_profilence_zeta_NodeAdded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_NodeAdded_descriptor,
        new java.lang.String[] { "NodeId", "Pool", "Type", "Variables", });
    internal_static_profilence_zeta_NodeRemoved_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_profilence_zeta_NodeRemoved_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_NodeRemoved_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_profilence_zeta_NodeUpdated_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_profilence_zeta_NodeUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_NodeUpdated_descriptor,
        new java.lang.String[] { "NodeId", "CurrentUseCase", "RunState", "CurrentRunId", "NodeState", "Pool", "Variables", });
    internal_static_profilence_zeta_DynamicSeriesInformation_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_profilence_zeta_DynamicSeriesInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DynamicSeriesInformation_descriptor,
        new java.lang.String[] { "RunId", "SeriesId", "SeriesName", "Group", "YAxisName", "Unit", "Type", "Namespace", "Process", "Description", });
    internal_static_profilence_zeta_DynamicSingleSeriesUpdate_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_profilence_zeta_DynamicSingleSeriesUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DynamicSingleSeriesUpdate_descriptor,
        new java.lang.String[] { "RunId", "SeriesId", "Timestamp", "Value", });
    internal_static_profilence_zeta_DynamicProcessSingleSeriesUpdate_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_profilence_zeta_DynamicProcessSingleSeriesUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DynamicProcessSingleSeriesUpdate_descriptor,
        new java.lang.String[] { "RunId", "SeriesId", "Package", "Process", "Timestamp", "Value", "Pid", });
    internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_descriptor,
        new java.lang.String[] { "RunId", "SeriesId", "Timestamp", "Values", });
    internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_ValuesEntry_descriptor =
      internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_descriptor.getNestedTypes().get(0);
    internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DynamicCompositeSeriesUpdate_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_descriptor,
        new java.lang.String[] { "RunId", "SeriesId", "Package", "Process", "Timestamp", "Values", "Pid", });
    internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_ValuesEntry_descriptor =
      internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_descriptor.getNestedTypes().get(0);
    internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_profilence_zeta_DeviceLogEntry_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_profilence_zeta_DeviceLogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_DeviceLogEntry_descriptor,
        new java.lang.String[] { "RunId", "DeviceIndex", "Timestamp", "Tag", "Data", "Priority", "SourceBuffer", });
    internal_static_profilence_zeta_ResetEntry_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_profilence_zeta_ResetEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_ResetEntry_descriptor,
        new java.lang.String[] { "RunId", "Timestamp", "Type", "Reasons", "Properties", });
    internal_static_profilence_zeta_ResetEntry_ReasonsEntry_descriptor =
      internal_static_profilence_zeta_ResetEntry_descriptor.getNestedTypes().get(0);
    internal_static_profilence_zeta_ResetEntry_ReasonsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_ResetEntry_ReasonsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_profilence_zeta_ResetEntry_PropertiesEntry_descriptor =
      internal_static_profilence_zeta_ResetEntry_descriptor.getNestedTypes().get(1);
    internal_static_profilence_zeta_ResetEntry_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_ResetEntry_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_profilence_zeta_EventEntry_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_profilence_zeta_EventEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_EventEntry_descriptor,
        new java.lang.String[] { "RunId", "Timestamp", "Type", "IsSystemProcess", "Name", "Process", "ExceptionType", "Data", });
    internal_static_profilence_zeta_PingRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_profilence_zeta_PingRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profilence_zeta_PingRunRequest_descriptor,
        new java.lang.String[] { "RunId", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
