// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface DynamicSingleSeriesUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.DynamicSingleSeriesUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>string series_id = 2;</code>
   * @return The seriesId.
   */
  java.lang.String getSeriesId();
  /**
   * <code>string series_id = 2;</code>
   * @return The bytes for seriesId.
   */
  com.google.protobuf.ByteString
      getSeriesIdBytes();

  /**
   * <code>double timestamp = 3;</code>
   * @return The timestamp.
   */
  double getTimestamp();

  /**
   * <code>float value = 4;</code>
   * @return The value.
   */
  float getValue();
}
