// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

/**
 * Protobuf type {@code profilence.zeta.DynamicProcessCompositeSeriesUpdate}
 */
public  final class DynamicProcessCompositeSeriesUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:profilence.zeta.DynamicProcessCompositeSeriesUpdate)
    DynamicProcessCompositeSeriesUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DynamicProcessCompositeSeriesUpdate.newBuilder() to construct.
  private DynamicProcessCompositeSeriesUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DynamicProcessCompositeSeriesUpdate() {
    runId_ = "";
    seriesId_ = "";
    package_ = "";
    process_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DynamicProcessCompositeSeriesUpdate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DynamicProcessCompositeSeriesUpdate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            runId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            seriesId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            package_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            process_ = s;
            break;
          }
          case 41: {

            timestamp_ = input.readDouble();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              values_ = com.google.protobuf.MapField.newMapField(
                  ValuesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
            values__ = input.readMessage(
                ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            values_.getMutableMap().put(
                values__.getKey(), values__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetValues();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.profilence.zeta.DynamicProcessCompositeSeriesUpdate.class, com.profilence.zeta.DynamicProcessCompositeSeriesUpdate.Builder.class);
  }

  public static final int RUN_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object runId_;
  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  public java.lang.String getRunId() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runId_ = s;
      return s;
    }
  }
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERIES_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object seriesId_;
  /**
   * <code>string series_id = 2;</code>
   * @return The seriesId.
   */
  public java.lang.String getSeriesId() {
    java.lang.Object ref = seriesId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      seriesId_ = s;
      return s;
    }
  }
  /**
   * <code>string series_id = 2;</code>
   * @return The bytes for seriesId.
   */
  public com.google.protobuf.ByteString
      getSeriesIdBytes() {
    java.lang.Object ref = seriesId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      seriesId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object package_;
  /**
   * <code>string package = 3;</code>
   * @return The package.
   */
  public java.lang.String getPackage() {
    java.lang.Object ref = package_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      package_ = s;
      return s;
    }
  }
  /**
   * <code>string package = 3;</code>
   * @return The bytes for package.
   */
  public com.google.protobuf.ByteString
      getPackageBytes() {
    java.lang.Object ref = package_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      package_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object process_;
  /**
   * <code>string process = 4;</code>
   * @return The process.
   */
  public java.lang.String getProcess() {
    java.lang.Object ref = process_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      process_ = s;
      return s;
    }
  }
  /**
   * <code>string process = 4;</code>
   * @return The bytes for process.
   */
  public com.google.protobuf.ByteString
      getProcessBytes() {
    java.lang.Object ref = process_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      process_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private double timestamp_;
  /**
   * <code>double timestamp = 5;</code>
   * @return The timestamp.
   */
  public double getTimestamp() {
    return timestamp_;
  }

  public static final int VALUES_FIELD_NUMBER = 6;
  private static final class ValuesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Float> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Float>newDefaultInstance(
                com.profilence.zeta.DriverProto.internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_ValuesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.FLOAT,
                0F);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Float> values_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
  internalGetValues() {
    if (values_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValuesDefaultEntryHolder.defaultEntry);
    }
    return values_;
  }

  public int getValuesCount() {
    return internalGetValues().getMap().size();
  }
  /**
   * <code>map&lt;string, float&gt; values = 6;</code>
   */

  public boolean containsValues(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetValues().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Float> getValues() {
    return getValuesMap();
  }
  /**
   * <code>map&lt;string, float&gt; values = 6;</code>
   */

  public java.util.Map<java.lang.String, java.lang.Float> getValuesMap() {
    return internalGetValues().getMap();
  }
  /**
   * <code>map&lt;string, float&gt; values = 6;</code>
   */

  public float getValuesOrDefault(
      java.lang.String key,
      float defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Float> map =
        internalGetValues().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, float&gt; values = 6;</code>
   */

  public float getValuesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Float> map =
        internalGetValues().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRunIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, runId_);
    }
    if (!getSeriesIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, seriesId_);
    }
    if (!getPackageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, package_);
    }
    if (!getProcessBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, process_);
    }
    if (timestamp_ != 0D) {
      output.writeDouble(5, timestamp_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetValues(),
        ValuesDefaultEntryHolder.defaultEntry,
        6);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRunIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, runId_);
    }
    if (!getSeriesIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, seriesId_);
    }
    if (!getPackageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, package_);
    }
    if (!getProcessBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, process_);
    }
    if (timestamp_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, timestamp_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Float> entry
         : internalGetValues().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
      values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, values__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.profilence.zeta.DynamicProcessCompositeSeriesUpdate)) {
      return super.equals(obj);
    }
    com.profilence.zeta.DynamicProcessCompositeSeriesUpdate other = (com.profilence.zeta.DynamicProcessCompositeSeriesUpdate) obj;

    if (!getRunId()
        .equals(other.getRunId())) return false;
    if (!getSeriesId()
        .equals(other.getSeriesId())) return false;
    if (!getPackage()
        .equals(other.getPackage())) return false;
    if (!getProcess()
        .equals(other.getProcess())) return false;
    if (java.lang.Double.doubleToLongBits(getTimestamp())
        != java.lang.Double.doubleToLongBits(
            other.getTimestamp())) return false;
    if (!internalGetValues().equals(
        other.internalGetValues())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RUN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRunId().hashCode();
    hash = (37 * hash) + SERIES_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSeriesId().hashCode();
    hash = (37 * hash) + PACKAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPackage().hashCode();
    hash = (37 * hash) + PROCESS_FIELD_NUMBER;
    hash = (53 * hash) + getProcess().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTimestamp()));
    if (!internalGetValues().getMap().isEmpty()) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetValues().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.profilence.zeta.DynamicProcessCompositeSeriesUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profilence.zeta.DynamicProcessCompositeSeriesUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profilence.zeta.DynamicProcessCompositeSeriesUpdate)
      com.profilence.zeta.DynamicProcessCompositeSeriesUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.profilence.zeta.DynamicProcessCompositeSeriesUpdate.class, com.profilence.zeta.DynamicProcessCompositeSeriesUpdate.Builder.class);
    }

    // Construct using com.profilence.zeta.DynamicProcessCompositeSeriesUpdate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      runId_ = "";

      seriesId_ = "";

      package_ = "";

      process_ = "";

      timestamp_ = 0D;

      internalGetMutableValues().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.profilence.zeta.DriverProto.internal_static_profilence_zeta_DynamicProcessCompositeSeriesUpdate_descriptor;
    }

    @java.lang.Override
    public com.profilence.zeta.DynamicProcessCompositeSeriesUpdate getDefaultInstanceForType() {
      return com.profilence.zeta.DynamicProcessCompositeSeriesUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public com.profilence.zeta.DynamicProcessCompositeSeriesUpdate build() {
      com.profilence.zeta.DynamicProcessCompositeSeriesUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.profilence.zeta.DynamicProcessCompositeSeriesUpdate buildPartial() {
      com.profilence.zeta.DynamicProcessCompositeSeriesUpdate result = new com.profilence.zeta.DynamicProcessCompositeSeriesUpdate(this);
      int from_bitField0_ = bitField0_;
      result.runId_ = runId_;
      result.seriesId_ = seriesId_;
      result.package_ = package_;
      result.process_ = process_;
      result.timestamp_ = timestamp_;
      result.values_ = internalGetValues();
      result.values_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.profilence.zeta.DynamicProcessCompositeSeriesUpdate) {
        return mergeFrom((com.profilence.zeta.DynamicProcessCompositeSeriesUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.profilence.zeta.DynamicProcessCompositeSeriesUpdate other) {
      if (other == com.profilence.zeta.DynamicProcessCompositeSeriesUpdate.getDefaultInstance()) return this;
      if (!other.getRunId().isEmpty()) {
        runId_ = other.runId_;
        onChanged();
      }
      if (!other.getSeriesId().isEmpty()) {
        seriesId_ = other.seriesId_;
        onChanged();
      }
      if (!other.getPackage().isEmpty()) {
        package_ = other.package_;
        onChanged();
      }
      if (!other.getProcess().isEmpty()) {
        process_ = other.process_;
        onChanged();
      }
      if (other.getTimestamp() != 0D) {
        setTimestamp(other.getTimestamp());
      }
      internalGetMutableValues().mergeFrom(
          other.internalGetValues());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.profilence.zeta.DynamicProcessCompositeSeriesUpdate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.profilence.zeta.DynamicProcessCompositeSeriesUpdate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object runId_ = "";
    /**
     * <code>string run_id = 1;</code>
     * @return The runId.
     */
    public java.lang.String getRunId() {
      java.lang.Object ref = runId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string run_id = 1;</code>
     * @return The bytes for runId.
     */
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      java.lang.Object ref = runId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      runId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      
      runId_ = getDefaultInstance().getRunId();
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      runId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object seriesId_ = "";
    /**
     * <code>string series_id = 2;</code>
     * @return The seriesId.
     */
    public java.lang.String getSeriesId() {
      java.lang.Object ref = seriesId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seriesId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string series_id = 2;</code>
     * @return The bytes for seriesId.
     */
    public com.google.protobuf.ByteString
        getSeriesIdBytes() {
      java.lang.Object ref = seriesId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seriesId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string series_id = 2;</code>
     * @param value The seriesId to set.
     * @return This builder for chaining.
     */
    public Builder setSeriesId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      seriesId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string series_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeriesId() {
      
      seriesId_ = getDefaultInstance().getSeriesId();
      onChanged();
      return this;
    }
    /**
     * <code>string series_id = 2;</code>
     * @param value The bytes for seriesId to set.
     * @return This builder for chaining.
     */
    public Builder setSeriesIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      seriesId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object package_ = "";
    /**
     * <code>string package = 3;</code>
     * @return The package.
     */
    public java.lang.String getPackage() {
      java.lang.Object ref = package_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        package_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string package = 3;</code>
     * @return The bytes for package.
     */
    public com.google.protobuf.ByteString
        getPackageBytes() {
      java.lang.Object ref = package_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        package_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string package = 3;</code>
     * @param value The package to set.
     * @return This builder for chaining.
     */
    public Builder setPackage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      package_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string package = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackage() {
      
      package_ = getDefaultInstance().getPackage();
      onChanged();
      return this;
    }
    /**
     * <code>string package = 3;</code>
     * @param value The bytes for package to set.
     * @return This builder for chaining.
     */
    public Builder setPackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      package_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object process_ = "";
    /**
     * <code>string process = 4;</code>
     * @return The process.
     */
    public java.lang.String getProcess() {
      java.lang.Object ref = process_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        process_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string process = 4;</code>
     * @return The bytes for process.
     */
    public com.google.protobuf.ByteString
        getProcessBytes() {
      java.lang.Object ref = process_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        process_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string process = 4;</code>
     * @param value The process to set.
     * @return This builder for chaining.
     */
    public Builder setProcess(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      process_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string process = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcess() {
      
      process_ = getDefaultInstance().getProcess();
      onChanged();
      return this;
    }
    /**
     * <code>string process = 4;</code>
     * @param value The bytes for process to set.
     * @return This builder for chaining.
     */
    public Builder setProcessBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      process_ = value;
      onChanged();
      return this;
    }

    private double timestamp_ ;
    /**
     * <code>double timestamp = 5;</code>
     * @return The timestamp.
     */
    public double getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>double timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(double value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Float> values_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
    internalGetMutableValues() {
      onChanged();;
      if (values_ == null) {
        values_ = com.google.protobuf.MapField.newMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      if (!values_.isMutable()) {
        values_ = values_.copy();
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, float&gt; values = 6;</code>
     */

    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Float> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, float&gt; values = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Float> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, float&gt; values = 6;</code>
     */

    public float getValuesOrDefault(
        java.lang.String key,
        float defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, float&gt; values = 6;</code>
     */

    public float getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearValues() {
      internalGetMutableValues().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, float&gt; values = 6;</code>
     */

    public Builder removeValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableValues().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Float>
    getMutableValues() {
      return internalGetMutableValues().getMutableMap();
    }
    /**
     * <code>map&lt;string, float&gt; values = 6;</code>
     */
    public Builder putValues(
        java.lang.String key,
        float value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      internalGetMutableValues().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, float&gt; values = 6;</code>
     */

    public Builder putAllValues(
        java.util.Map<java.lang.String, java.lang.Float> values) {
      internalGetMutableValues().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:profilence.zeta.DynamicProcessCompositeSeriesUpdate)
  }

  // @@protoc_insertion_point(class_scope:profilence.zeta.DynamicProcessCompositeSeriesUpdate)
  private static final com.profilence.zeta.DynamicProcessCompositeSeriesUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.profilence.zeta.DynamicProcessCompositeSeriesUpdate();
  }

  public static com.profilence.zeta.DynamicProcessCompositeSeriesUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DynamicProcessCompositeSeriesUpdate>
      PARSER = new com.google.protobuf.AbstractParser<DynamicProcessCompositeSeriesUpdate>() {
    @java.lang.Override
    public DynamicProcessCompositeSeriesUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DynamicProcessCompositeSeriesUpdate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DynamicProcessCompositeSeriesUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DynamicProcessCompositeSeriesUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.profilence.zeta.DynamicProcessCompositeSeriesUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

