// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface EventEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.EventEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>double timestamp = 2;</code>
   * @return The timestamp.
   */
  double getTimestamp();

  /**
   * <code>int32 type = 3;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>bool is_system_process = 4;</code>
   * @return The isSystemProcess.
   */
  boolean getIsSystemProcess();

  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string process = 6;</code>
   * @return The process.
   */
  java.lang.String getProcess();
  /**
   * <code>string process = 6;</code>
   * @return The bytes for process.
   */
  com.google.protobuf.ByteString
      getProcessBytes();

  /**
   * <code>string exception_type = 7;</code>
   * @return The exceptionType.
   */
  java.lang.String getExceptionType();
  /**
   * <code>string exception_type = 7;</code>
   * @return The bytes for exceptionType.
   */
  com.google.protobuf.ByteString
      getExceptionTypeBytes();

  /**
   * <code>repeated string data = 8;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.String>
      getDataList();
  /**
   * <code>repeated string data = 8;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated string data = 8;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  java.lang.String getData(int index);
  /**
   * <code>repeated string data = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the data at the given index.
   */
  com.google.protobuf.ByteString
      getDataBytes(int index);
}
