// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface TestStartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.TestStartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string run_id = 22;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 22;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>string run_name = 2;</code>
   * @return The runName.
   */
  java.lang.String getRunName();
  /**
   * <code>string run_name = 2;</code>
   * @return The bytes for runName.
   */
  com.google.protobuf.ByteString
      getRunNameBytes();

  /**
   * <code>string node_id = 5;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 5;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string project = 10;</code>
   * @return The project.
   */
  java.lang.String getProject();
  /**
   * <code>string project = 10;</code>
   * @return The bytes for project.
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string version = 16;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 16;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string test_set_file_path = 12;</code>
   * @return The testSetFilePath.
   */
  java.lang.String getTestSetFilePath();
  /**
   * <code>string test_set_file_path = 12;</code>
   * @return The bytes for testSetFilePath.
   */
  com.google.protobuf.ByteString
      getTestSetFilePathBytes();

  /**
   * <code>bytes payload = 14;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>map&lt;string, string&gt; tags = 20;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 20;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 20;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 20;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 20;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string log = 24;</code>
   * @return A list containing the log.
   */
  java.util.List<java.lang.String>
      getLogList();
  /**
   * <code>repeated string log = 24;</code>
   * @return The count of log.
   */
  int getLogCount();
  /**
   * <code>repeated string log = 24;</code>
   * @param index The index of the element to return.
   * @return The log at the given index.
   */
  java.lang.String getLog(int index);
  /**
   * <code>repeated string log = 24;</code>
   * @param index The index of the value to return.
   * @return The bytes of the log at the given index.
   */
  com.google.protobuf.ByteString
      getLogBytes(int index);
}
