// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface TestStartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.TestStartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>string fail_cause = 2;</code>
   * @return The failCause.
   */
  java.lang.String getFailCause();
  /**
   * <code>string fail_cause = 2;</code>
   * @return The bytes for failCause.
   */
  com.google.protobuf.ByteString
      getFailCauseBytes();

  /**
   * <code>repeated string log = 3;</code>
   * @return A list containing the log.
   */
  java.util.List<java.lang.String>
      getLogList();
  /**
   * <code>repeated string log = 3;</code>
   * @return The count of log.
   */
  int getLogCount();
  /**
   * <code>repeated string log = 3;</code>
   * @param index The index of the element to return.
   * @return The log at the given index.
   */
  java.lang.String getLog(int index);
  /**
   * <code>repeated string log = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the log at the given index.
   */
  com.google.protobuf.ByteString
      getLogBytes(int index);

  /**
   * <code>bool result = 4;</code>
   * @return The result.
   */
  boolean getResult();

  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
