// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface UseCaseEndRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.UseCaseEndRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>bool result = 2;</code>
   * @return The result.
   */
  boolean getResult();

  /**
   * <code>int64 activeRunTime = 3;</code>
   * @return The activeRunTime.
   */
  long getActiveRunTime();

  /**
   * <code>string fail_cause = 4;</code>
   * @return The failCause.
   */
  java.lang.String getFailCause();
  /**
   * <code>string fail_cause = 4;</code>
   * @return The bytes for failCause.
   */
  com.google.protobuf.ByteString
      getFailCauseBytes();

  /**
   * <code>bool reset_intended = 5;</code>
   * @return The resetIntended.
   */
  boolean getResetIntended();
}
