// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector_service.proto

package com.profilence.zeta;

public interface UseCaseStartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profilence.zeta.UseCaseStartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>string use_case_name = 2;</code>
   * @return The useCaseName.
   */
  java.lang.String getUseCaseName();
  /**
   * <code>string use_case_name = 2;</code>
   * @return The bytes for useCaseName.
   */
  com.google.protobuf.ByteString
      getUseCaseNameBytes();

  /**
   * <code>string use_case_id = 3;</code>
   * @return The useCaseId.
   */
  java.lang.String getUseCaseId();
  /**
   * <code>string use_case_id = 3;</code>
   * @return The bytes for useCaseId.
   */
  com.google.protobuf.ByteString
      getUseCaseIdBytes();

  /**
   * <code>string target_process = 4;</code>
   * @return The targetProcess.
   */
  java.lang.String getTargetProcess();
  /**
   * <code>string target_process = 4;</code>
   * @return The bytes for targetProcess.
   */
  com.google.protobuf.ByteString
      getTargetProcessBytes();

  /**
   * <code>string requirement_id = 5;</code>
   * @return The requirementId.
   */
  java.lang.String getRequirementId();
  /**
   * <code>string requirement_id = 5;</code>
   * @return The bytes for requirementId.
   */
  com.google.protobuf.ByteString
      getRequirementIdBytes();

  /**
   * <code>int32 test_type = 6;</code>
   * @return The testType.
   */
  int getTestType();

  /**
   * <code>string test_case_group_name = 7;</code>
   * @return The testCaseGroupName.
   */
  java.lang.String getTestCaseGroupName();
  /**
   * <code>string test_case_group_name = 7;</code>
   * @return The bytes for testCaseGroupName.
   */
  com.google.protobuf.ByteString
      getTestCaseGroupNameBytes();

  /**
   * <code>string test_set_name = 8;</code>
   * @return The testSetName.
   */
  java.lang.String getTestSetName();
  /**
   * <code>string test_set_name = 8;</code>
   * @return The bytes for testSetName.
   */
  com.google.protobuf.ByteString
      getTestSetNameBytes();
}
